version: "2.4"
services:
  mongodb:
    image: "mongo:latest"
    container_name: mongodb
    hostname: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepwd
    ports:
      - 27017:27017

  sample-flask:
#    image: "signoz/sample-flask-app:latest"
    build: .
    container_name: sample-flask
    hostname: sample-flask
    ports:
      - 5002:5002
    environment:
      MONGO_URI: mongodb://root:examplepwd@mongodb:27017
      OTEL_RESOURCE_ATTRIBUTES: service.name=sample-flask
      OTEL_EXPORTER_OTLP_ENDPOINT: http://192.168.8.204:4317  # Replace to appropriate SigNoz OtelCollector endpoint, if applicable
      OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED: true
